### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by M3rsy** [Linux-Theme-Collection/Windows-Manager#1]
WHat kind of icons use?

**Comment by YangMame** [comment]
I use this one
https://github.com/Linux-Theme-Collection/Windows-Manager/blob/750d781e708c262467aee58b742b6ab14494d1cd/gtk-3.0/settings.ini#L3

**Comment by M3rsy** [comment]
@M3rsy Thanks Bro

**Comment by M3rsy** [comment]
@YangMame Thanks Sir

**Comment by YangMame** [comment]
you are welcome ;-)
